matplot(data[ , 7:9], type = "l", axes = F, xlab="", ylab = "Energy sub metering", col=c("black", "red", "blue"))
axis(1, at = c(1, nrow(data)/2+1, nrow(data)+1), labels=F)
text(y=par('usr')[3]-(par('usr')[4]-par('usr')[3])/7, x = c(1, nrow(data)/2+1, nrow(data)+1), labels = c("Thu", "Fri", "Sat"), xpd=T)
axis(2)
box()
legend("topright", legend=colnames(data)[7:9], border=NA, lwd=1, col=c("black", "red", "blue"))
dev.copy(png, "plot3.png")
dev.off()